anno/urls.py
from django.contrib import admin
from django.urls import path, include
from dotenv import load_dotenv
from django.shortcuts import redirect
import os
from django.conf.urls.static import static
from . import settings

load_dotenv()

urlpatterns = [
    path('', lambda request: redirect('asrann/', permanent=True)),
    path('asrann/', include("asrann.urls")),
    path(os.getenv("ADMIN_ROUTE"), admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

asrann/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.admin.views.decorators import staff_member_required


LOGIN_URL='/asrann/login'

app_name = "asrann"
urlpatterns = [
    path("", login_required(views.IndexView.as_view(), login_url=LOGIN_URL), name="index"), #dataset
    path("<uuid:dataset_pk>/", staff_member_required(login_required(views.RecordsView.as_view(), login_url=LOGIN_URL), login_url="/asrann"), name="records"),
    path("tagged/", login_required(views.TaggedView.as_view(), login_url=LOGIN_URL), name="tagged"),
    path("tagging/", login_required(views.tagging, login_url=LOGIN_URL), name="tagging"),
    path("report/", login_required(views.report, login_url=LOGIN_URL), name="report"),
    path("ureport/", staff_member_required(login_required(views.ureport, login_url=LOGIN_URL)), name="ureport"),
    path("record/<uuid:pk>/", login_required(views.singleRecord, login_url=LOGIN_URL), name="record"),
    #path("<int:dataset_pk>/record/<int:pk>/next/", login_required(views.goto_next, login_url=LOGIN_URL), name="next_rec"), 
    #path("<int:dataset_pk>/record/<int:pk>/prev/", login_required(views.goto_prev, login_url=LOGIN_URL), name="prev_rec"),
    path("record/<uuid:pk>/vote/", login_required(views.vote, login_url=LOGIN_URL), name="vote"),
    path('record/<uuid:pk>/audio/', login_required(views.serve_audio_from_tar, login_url=LOGIN_URL), name='serve_audio'),
    path('login/', views.sign_in, name='login'),
    path('register/', views.sign_up, name='register'),
    path('logout/', views.sign_out, name='logout'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',  
        views.activate, name='activate'),  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

asrann/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import Sum
import uuid

User._meta.get_field('email')._unique = True

class Dataset(models.Model):
    id = models.UUIDField( 
         primary_key = True, 
         default = uuid.uuid4, 
         editable = False)
    
    gzip = "gzip"
    zip = "zip"
    tar = "tar"
    rar = "rar"
    bzip = "bzip2"
    wim = "wim"
    xz = "xz"
    sevenz = "7z"
    none = "none"
    COMPRESSED_TYPES = {
        gzip: "gzip",
        zip: "zip",
        tar: "tar",
        rar: "rar",
        bzip: "bzip2",
        wim: "wim",
        xz: "xz",
        sevenz: "7z",
        none: "none"
    }
    name = models.CharField(max_length=200, default="unknown")
    version = models.CharField(max_length=50, default="0.1.0")
    data_folder = models.CharField(max_length=200, default=".")
    add_date = models.DateTimeField("date added")
    added_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    is_compressed = models.CharField(default="none", max_length=5, choices=COMPRESSED_TYPES)
    def __str__(self):
        return self.name


class Record(models.Model):
    id = models.UUIDField( 
         primary_key = True, 
         default = uuid.uuid4, 
         editable = False)
    audio_file = models.CharField(max_length=200)
    transcription = models.TextField()

    add_date = models.DateTimeField("date added", default=timezone.now)
    #added_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    tar_file = models.SmallIntegerField(default=0, blank=True, null=True)
    def __str__(self):
        return self.audio_file

class Vote(models.Model):
    class VoteChoices(models.IntegerChoices):
        up = 1
        down = -1
    record = models.ForeignKey(Record, on_delete=models.CASCADE)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    vote = models.IntegerField(default=0)
    vote_date = models.DateTimeField("date voted")
    def __str__(self):
        user_vote = "UP" if self.vote == 1 else "DOWN"
        return "Vote " + " on " + self.record.audio_file + " (" + self.record.dataset.name + ") by " + self.added_by.username + ", " + user_vote

@receiver(post_save, sender=Vote)
def update_record_score(sender, instance, created, **kwargs):
    record = instance.record
    record_score = abs(Vote.objects.filter(record=record).aggregate(Sum('vote'))['vote__sum'])
    Record.objects.filter(id=record.id).update(score = record_score)
    print(sender)
    print('instance:', record)
    print('score: ', record_score)

class ActiveDataset(models.Model):
    dataset = models.ForeignKey(Dataset, on_delete=models.DO_NOTHING)
    def __str__(self):
        return self.dataset.name

class AppConfig(models.Model):
    autoplay = models.BooleanField(default=True)

class CustomUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    score_weight = models.IntegerField(default=1)#, blank=False, null=False)
    user_tested = models.BooleanField(default=False)
    passed_score = models.IntegerField(default=10)

@receiver(post_save, sender=User)
def update_user_score(sender, instance, created, **kwargs):
    print('sender:', sender)
    print('instance:', instance)
    try:
        cuser = CustomUser.objects.get(user=instance)
        print('cuser:', cuser)
        print('new weight:', cuser.score_weight)
    except CustomUser.DoesNotExist as e:
        print('create custom user')
        print('error: ', e)
        cuser = CustomUser(user=instance, score_weight=1)
        cuser.save()

asrann/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

class LoginForm(forms.Form):
    email = forms.EmailField(max_length=2000, label="آدرس ایمیل")
    password = forms.CharField(max_length=65, widget=forms.PasswordInput, label="کلمه عبور")

class RegisterForm(UserCreationForm):
    password1 = forms.CharField(max_length=65, widget=forms.PasswordInput, label="کلمه عبور")
    password2 = forms.CharField(max_length=65, widget=forms.PasswordInput, label="تکرار کلمه")
    email = forms.EmailField(max_length=200, help_text='Required', label='آدرس ایمیل')  
    class Meta:
        model=User
        #username = forms.CharField(max_length=65, label="نام کاربری")
        #email = forms.CharField(max_length=65, widget=forms.EmailInput, label='پست الکترونیک')
        
        fields = ['email']
        labels = {
            #'username': _('نام کاربری'),
            #'email': _('پست الکترونیک'),
            #'password1': _('رمز عبور'),
            #'password2': _('تکرار رمز')
        }
        
#from https://www.pythontutorial.net/django-tutorial/django-login/
#from https://www.pythontutorial.net/django-tutorial/django-registration/

asrann/views.py
from django.shortcuts import render, redirect
from datetime import datetime
from django.views import generic
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from .models import Dataset, Record, Vote, ActiveDataset, CustomUser
from django.shortcuts import get_object_or_404, render
from django.db.models import F
from django.urls import reverse
import pprint
from django.utils import timezone
from django.db.models import Q
import os
from django.conf import settings
import tarfile
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from .forms import LoginForm, RegisterForm
from django.contrib.auth.decorators import permission_required
from django.db.models import Count, Case, When, IntegerField, Sum
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import random
from django.contrib.auth.models import User
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode 
from django.core.mail import EmailMessage    
from .token import account_activation_token  
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
import pprint
from dotenv import load_dotenv

load_dotenv()
SPLIT_PREFIX = os.getenv('SPLIT_PREFIX')
USE_EMAIL_VERIFICATION = os.getenv('USE_EMAIL_VERIFICATION', 'False').lower() in ('true')

SCORE_THRESHOLD = int(os.getenv('SCORE_THRESHOLD'))


class IndexView(generic.ListView):
    template_name = "asrann/index.html"
    context_object_name = "latest_assigned_datasets"
    paginate_by = 10
    def get_queryset(self):
        """Return the last five published datasets."""
        #self.request.session['prev_stack'] = []
        #self.request.session['next_stack'] = []
        return Dataset.objects.order_by("-add_date") #[:5]

class RecordsView(generic.ListView):
    #model = Dataset
    template_name = "asrann/records.html"
    context_object_name = "dataset_assigned_records"
    paginate_by = 10
    
    def get_queryset(self):
        """Return the last five published datasets."""
        #self.request.session['prev_stack'] = []
        print('kwargs:', self.kwargs)
        return Record.objects.filter(dataset_id=self.kwargs['dataset_pk']) #[:300]

class TaggedView(generic.ListView):
    model = Vote
    template_name = 'asrann/tagged_list.html'  # Default: <app_label>/<model_name>_list.html
    context_object_name = 'all_tagged_by_user'  # Default: object_list
    paginate_by = 10
    
    def get_queryset(self):
        #self.request.session['prev_stack'] = []
        #self.request.session['next_stack'] = []
        user = self.request.user
        return Vote.objects.filter(added_by=user)

#@login_required(login_url=LOGIN_URL)
def singleRecord(request, pk):
    
    user = request.user
    record = get_object_or_404(Record, pk=pk)
    vote = None

    try:
        vote = Vote.objects.get(record=record, added_by=user).vote
    except Vote.DoesNotExist:
        pass
    context = {
        "record": record,
        "vote": vote,
        "audio_file": record.audio_file,
        "static": False
    }
    if not user.customuser.user_tested:
        vote_meter = Vote.objects.filter(record=record).aggregate(Sum('vote'))['vote__sum']
        context["vote_meter"] = vote_meter
        context["remained_tests"] = user.customuser.passed_score

    return render(request, "asrann/single_record.html", context)

def vote(request, pk):
    
    votes = {
        'up': 1,
        'down': -1
    }
    vote = request.POST.get('vote')
    record = get_object_or_404(Record, pk=pk)
    user = request.user
    if vote:
        dt = timezone.now()
        if user.customuser.user_tested:
            vote = votes[vote] * request.user.customuser.score_weight
            v, created = Vote.objects.update_or_create(
                added_by = request.user,
                record = record,
                defaults = {"vote": vote, "vote_date": timezone.now()},
                create_defaults = {
                    "added_by": request.user,
                    "record": record,
                    "vote": vote,
                    "vote_date": timezone.now()
                }
            )
        else:
            vote = votes[vote]
            vote_meter = Vote.objects.filter(record=record).aggregate(Sum('vote'))['vote__sum']
            user_model = User.objects.get(id=user.id)
            passed_score = user_model.customuser.passed_score

            if (vote > 0 and vote_meter > 0) or (vote < 0 and vote_meter < 0):
                custom_user = CustomUser.objects.get(user=user_model)
                if passed_score - 1 <= 0:
                    custom_user.user_tested = True
                custom_user.passed_score = passed_score - 1
                custom_user.save()
    return goto_next(request, pk, record.add_date)

def goto_next(request, pk, add_date):
    
    user = request.user
    try:
        active = get_object_or_404(ActiveDataset.objects.order_by('?')[:1])
        #record = Record.objects.filter(~Q(vote__added_by=user)).filter(add_date__gt=add_date).filter(score__lt=SCORE_THRESHOLD).order_by("-score")
        if not user.customuser.user_tested:
            records = Record.objects.filter(score__gte=SCORE_THRESHOLD)
            record = random.choice(records)
            return HttpResponseRedirect(reverse("asrann:record", args=(record.id,)))    
        records = Record.objects.filter(~Q(vote__added_by=user)).filter(score__lt=SCORE_THRESHOLD, dataset=active.dataset).order_by("-score")
        return HttpResponseRedirect(reverse("asrann:record", args=(records[0].id,)))
    except (IndexError, Record.DoesNotExist):
        return redirect('/asrann/')
    
def goto_prev(request, dataset_pk, pk):
    
    next = request.session.get('next_stack')
    prev = request.session.get('prev_stack')
    #print('got-prev:prev', prev)
    #print('got-next:prev', prev)
    if next and len(next) > 0:
        next.append({
            "record": pk,
            "dataset": dataset_pk
        })
    else:
        next = [{
            "record": pk,
            "dataset": dataset_pk
        }]
    request.session['next_stack'] = next
    if len(prev) > 0:
        last_page = prev.pop()
        #request.session['prev_stack'] = prev
        return HttpResponseRedirect(reverse("asrann:record", args=(last_page['dataset'], last_page['record'],)))
    else:
        return HttpResponseRedirect(reverse("asrann:records", args=(dataset_pk,)))

def serve_audio_from_tar(request, pk):

    try:
        record = Record.objects.get(id=pk)
        tar_file_string_name = "data/" + SPLIT_PREFIX + "_" + "{:03d}".format(record.tar_file) + ".tar"
        dataset_folder = record.dataset.data_folder
        tar_file_path = settings.MEDIA_ROOT + dataset_folder + "/" + tar_file_string_name
        audio_file_name = record.audio_file
        with tarfile.open(tar_file_path, 'r') as tar:
            audio_file = tar.extractfile(audio_file_name)
            response = HttpResponse(content_type='audio/mpeg')
            #response['Content-Disposition'] = f'attachment; filename="{audio_file_name}"'
            response.write(audio_file.read())

        return response
    except Record.DoesNotExist:
        pass

def activate(request, uidb64, token):  
    try:  
        uid = force_str(urlsafe_base64_decode(uidb64))  
        user = User.objects.get(pk=uid)  
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):  
        user = None  
    if user is not None and account_activation_token.check_token(user, token):  
        user.is_active = True  
        user.save()  
        return HttpResponse("<div style='direction: rtl'><p>از تایید ایمیل‌تان ممنونیم. حالا میتوانید <a href='/asrann'>وارد شوید</a></p></div>")
        #return HttpResponse('Thank you for your email confirmation. Now you can login your account.')  
        
    else:  
        return HttpResponse('Activation link is invalid!')  
    
def sign_in(request):

    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/asrann')
        
        form = LoginForm()
        return render(request,'asrann/login.html', {'form': form})
    
    elif request.method == 'POST':
        form = LoginForm(request.POST)
        
        if form.is_valid():
            username = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request,username=username,password=password)
            if user:
                login(request, user)
                messages.success(request,f'Hi {username.title()}, welcome back!')
                return redirect('/asrann')
        
        # form is not valid or user is not authenticated
        messages.error(request,f'Invalid username or password')
        return render(request,'asrann/login.html',{'form': form})
    
def sign_out(request):
    logout(request)
    messages.success(request,f'You have been logged out.')
    return redirect('/asrann/login/')

def sign_up(request):
    if request.user.is_authenticated:
        return redirect('/asrann/')
    
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'asrann/register.html', { 'form': form})  
    
    if request.method == 'POST':
        form = RegisterForm(request.POST) 
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.email.lower()
            user.is_active = not USE_EMAIL_VERIFICATION
            user.save()

            if USE_EMAIL_VERIFICATION:
                messages.success(request, 'You have singed up successfully.')
                #login(request, user)
                #return redirect('/asrann/')
                current_site = get_current_site(request)  
                mail_subject = 'Activation link has been sent to your email id'  

asrann/templates/asrann/acc_active_email.html
{% autoescape off %}  
Hi {{ user.username }},  
Please click on the link to confirm your registration,  
http://{{ domain }}{% url 'asrann:activate' uidb64=uid token=token %}  
{% endautoescape %}  

asrann/templates/asrann/index.html
{% extends "base.html" %}

{% block title %}
{% if user.is_staff %}
دادگان
{% else %}
صفحه نخست
{% endif %}
{% endblock %}

{% block home %}
{% if user.is_staff %}
<a class="active">
    دادگان
</a>
{% endif %}
{% endblock %}

{% block content %}

{% if user.is_staff %}
<div class="page-heading">
    <h1>دادگان</h1>
</div>

<table class="responsive-table">
    <thead>
      <tr>
        <th>#</th>
        <th>نام</th>
        <th>نسخه</th>
        <th>پوشه</th>
        <th>تاریخ</th>
        <th>توسط</th>
    </tr>
    </thead>
    <tbody>
      {% for dataset in latest_assigned_datasets %}
      <tr>
        <td data-label="#">{{ forloop.counter0|add:page_obj.start_index }}</td>
        <td data-label="نام"><a href="/asrann/{{ dataset.id }}/">{{ dataset.name }}</a></td>
        <td data-label="نسخه">{{ dataset.version }}</td>
        <td data-label="پوشه">{{ dataset.data_folder }}</td>
        <td data-label="تاریخ">{{ dataset.add_date }}</td>
        <td data-label="توسط">{{ dataset.added_by }}</td>
    </tr>
      {% endfor %}
    </tbody>
  </table>
  
  {% if is_paginated %}
  <div style="">
    <ul class="pagination" style="flex-direction: row; display: flex;">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
</div>
  {% endif %}
{% endif %}
{% endblock %}

{% block extendsidebar %}
{% if user.is_staff %}
{% else %}
<script>
    document.getElementById("mySidenav").style.width = "100%";
    console.log('hi from tlate');
</script>
{% endif %}
{% endblock %}

asrann/templates/asrann/login.html
{% extends 'base.html' %}
{% block title %}ورود{% endblock %}
{% block content %}
<div class="container">
    <div id="card-frame">
        <form method="post">
            <h2>ورود</h2>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="ورود">
            <p>حساب کاربری ندارید؟ <a href="/asrann/register">یکی بسازید</a></p>
        </form>
    </div>
</div>
{% endblock content %}

asrann/templates/asrann/records.html
{% extends "base.html" %}

{% block title %}مجمومه داده {{dataset_assigned_records.0.dataset.name }}{% endblock %}

{% block current_dataset %}
{% if user.is_staff %}
<a class="active" style="padding-right: 30px;">{{dataset_assigned_records.0.dataset.name}}</a>
{% endif %}
{% endblock %}

{% block content %}

<div class="page-heading">
    <h1>مجموعه داده {{ dataset_assigned_records.0.dataset.name }}</h1>
</div>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th style="text-align: right;">#</th>
        <th style="text-align: right;">متن</th>
        <th style="text-align: right;">امتیاز</th>
        <th style="text-align: right;">مجموعه داده</th>
        <!--<th style="text-align: right;">تاریخ</th>-->
        <th style="text-align: right;">دیدن</th>
      </tr>
    </thead>
    <tbody>
      {% for record in dataset_assigned_records %}
        <tr>
          <td data-label="#">{{ forloop.counter0|add:page_obj.start_index }}</td>
          <td data-label="متن">{{ record.transcription }}</td>
          <td data-label="امتیاز">{{ record.score }}</td>
          <!--<td>{{ record.dataset.name }}</td>-->
          <td data-label="مجموعه داده">{{ record.add_date }}</td>
          <td data-label="دیدن"><a href="/asrann/record/{{ record.id }}/">دیدن</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
  
   <!--<div>
    {% if all_tagged_by_user %}
        تعداد همه آراء ثبت شده شما: {{ all_tagged_by_user|length }}
    {% else %}
        No athletes.
    {% endif %}
    </div>-->

  {% if is_paginated %}
  <div class="pagination"  style="flex-direction: row; display: flex; margin-right: 50px;">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">قبلی</a>
        {% endif %}

        <span class="current">
            صفحه {{ page_obj.number }} از {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">بعدی</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
  {% endif %}

{% endblock %}

asrann/templates/asrann/register.html
{% extends 'base.html' %}
{% block title %}ثبت نام{% endblock %}
{% block content %}
<div class="container">
    <div class="card-frame">
        <form method="post">
            {% csrf_token %}
            <h2>ثبت نام</h2>
            {% for field in form %}
                {% if field.errors %}
                    {% for error in field.errors %}
                        <div class="error-message">{{ error }}</div>
                    {% endfor %}
                {% endif %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endfor %}
            <input type="submit" value="ثبت نام">
            <p>حساب کاربری دارید؟ <a href="/asrann/login">وارد شوید</a></p>
        </form>
    </div>
</div>
{% endblock content%}

asrann/templates/asrann/report.html
{% extends "base.html" %}

{% block title %}
گزارش
{% endblock %}

{% block report %}
<a class="active">
  گزارش
</a>
{% endblock %}

{% block content %}

<div class="page-heading">
  <h1>گزارش</h1>
</div>
<div clas="container">
  <div style="text-align: center;">
    <div style="text-align: right; font-family: Tahoma; font-size: 18px; display: inline-block;">
      <ul>
        <li>همه برچسب‌های شما: {{ your_records_count }}</li>
        {% if user.is_staff and first_page %}
        <li>مجموعه همه رکوردها: {{combined_records_count}}</li>
        {% for score, c in distinct_scores_all.items %}
        <li>تعداد رکورد ها با اسکور {{score}}: {{c}}</li>
        {% endfor %}
      </ul>
      به تفکیک دادگان
      <ul>
        {% for active_dataset in datasets_features %}
        <li>مجموعه دادگان: <b>{{active_dataset.active_dataset}}</b></li>
        <ul>
          <li>تعداد رکوردها: {{active_dataset.active_dataset_records}}</li>
          {% for score, c in active_dataset.score_list.items %}
          <li>تعداد رکورد ها با اسکور {{score}}: {{c}}</li>
          {% endfor %}
        </ul>
        {% endfor %}
        {% endif %}
      </ul>
    </div>
  </div>
  {% if user.is_staff %}
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>متن</th>
          <th>up</th>
          <th>down</th>
          <th>score</th>
      </tr>
      </thead>
      <tbody>
        {% for vote in group_by_vote %}
        <tr>
          <td data-label="#">{{ forloop.counter0|add:group_by_vote.start_index }}</td>
          <td data-label="متن">{{ vote.transcription }}</td>
          {% if vote.up_votes > 0 %}
          <td  data-label="up"style="background: #28B463 ">{{vote.up_votes}}</a></td>
          {% else %}
          <td></td>
          {% endif %}
          {% if vote.down_votes > 0 %}
          <td  data-label="down"style="background: #E74C3C">{{vote.down_votes}}</td>
          {% else %}
          <td></td>
          {% endif %}
          <td data-label="score">{{vote.score}}</td>
          <!--{% if vote.vote__vote == None %}
            <td style="background: #ccefee">{{vote.vote_count}}</td>
          {% else %}
            <td></td>
          {% endif %}-->
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="pagination">
    <span class="step-links">
        {% if group_by_vote.has_previous %}
            <a href="?page=1">« first</a>
            <a href="?page={{ group_by_vote.previous_page_number }}">قبلی</a>
        {% endif %}
        <span class="current">
            صفحه {{ group_by_vote.number }} از {{ group_by_vote.paginator.num_pages }}.
        </span>
        {% if group_by_vote.has_next %}
            <a href="?page={{ group_by_vote.next_page_number }}">بعدی</a>
            <a href="?page={{ group_by_vote.paginator.num_pages }}">last »</a>
        {% endif %}
    </span>
  </div>

  {% endif %}
</div>
{% endblock %}

asrann/templates/asrann/ureport.html
{% extends "base.html" %}

{% block title %}
گزارش کاربران
{% endblock %}

{% block ureport %}
<a class="active">
  گزارش کاربران
</a>
{% endblock %}

{% block content %}

<div class="page-heading">
  <h1>گزارش کاربران</h1>
</div>
<div clas="container">

  {% if user.is_staff %}
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>کاربر</th>
          <th>تعداد رای</th>
      </tr>
      </thead>
      <tbody>
        {% for u, c in ulist.items %}
        <tr>
          <td data-label="کاربر">{{ u }}</td>
          <td data-label="تعداد رای">{{ c }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!--<div class="pagination">
    <span class="step-links">
        {% if ulist.has_previous %}
            <a href="?page=1">« first</a>
            <a href="?page={{ ulist.previous_page_number }}">قبلی</a>
        {% endif %}
        <span class="current">
            صفحه {{ ulist.number }} از {{ ulist.paginator.num_pages }}.
        </span>
        {% if ulist.has_next %}
            <a href="?page={{ ulist.next_page_number }}">بعدی</a>
            <a href="?page={{ ulist.paginator.num_pages }}">last »</a>
        {% endif %}
    </span>
  </div>-->

  {% endif %}
</div>
{% endblock %}